language: python

sudo: false

python:
    - 2.7

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install -U pip wheel
    - pip install -r requirements.txt -r dev_requirements.txt coveralls

script:
    - make lint-code
    - make coverage

after_script:
    - coveralls

branches:
  only:
    - master
